### PR TITLE
Initial build for 6.7.1 ❄️

### PR DESCRIPTION
**Pull request by JeanChristopheMorinPerso**
Upstream: https://github.com/seperman/deepdiff/tree/6.7.1

Channel: Snowflake

### CODE REVIEW

**Review by ryanskeith — APPROVED** [review]
LGTM

**Comment by lorepirri** [comment]
[PKG-3563]

**Review by lorepirri — APPROVED** [review]
LGTM,
doc_url: https://deepdiff.readthedocs.io

**Review by M-Waszkiewicz-Anaconda — APPROVED** [review]
LGTM

**Pull request merged**
